[package]
name = "factorio"
version = "0.1.0"
authors = ["Michal Zurkowski <michal.zurkowski@gmail.com>"]

[dependencies]
base64 = "0.9.1"
flate2 = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
